# Generated by Django 4.2.1 on 2023-06-11 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_question_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
