# Generated by Django 4.2.1 on 2023-06-25 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_answer_type_comment_type_question_type'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='Topic',
        ),
    ]
