# Generated by Django 4.2.1 on 2023-06-29 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_question_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='question',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic',
            new_name='title',
        ),
    ]
