# Generated by Django 4.2.3 on 2023-07-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_question_answer_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='no_answers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
