# Generated by Django 4.2.3 on 2023-07-17 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_topic_no_answers_topic_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='no_answers',
            new_name='is_article',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='private',
            new_name='is_private',
        ),
    ]
