# Generated by Django 4.2.3 on 2023-07-17 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_no_answers_topic_is_article_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
