# Generated by Django 4.2.3 on 2023-07-20 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_topic_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='scores',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='topic',
            name='scores',
            field=models.IntegerField(default=0),
        ),
    ]
