# Generated by Django 4.2.3 on 2023-07-26 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_answer_date_modified_comment_date_modified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='')),
                ('description', models.TextField(null=True)),
                ('topics', models.ManyToManyField(to='api.topic')),
            ],
        ),
    ]
