# Generated by Django 4.2.3 on 2023-07-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='tags', to='api.topic'),
        ),
    ]
