# Generated by Django 4.2.6 on 2023-10-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_tag_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['-date_created'], name='api_topic_date_cr_0f9121_idx'),
        ),
    ]
