# Generated by Django 4.2.6 on 2023-10-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='api_tag_name_38f172_idx'),
        ),
    ]
