# Generated by Django 4.2.6 on 2023-10-31 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_tag_options_tag_api_tag_name_38f172_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='is_private',
            field=models.CharField(default=False),
        ),
    ]
