# Generated by Django 4.2.6 on 2023-10-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_tag_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_protected',
            field=models.BooleanField(default=False),
        ),
    ]
