# Generated by Django 4.2.6 on 2023-11-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_topic_is_protected'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
