# Generated by Django 4.2.6 on 2023-11-05 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='is_protected',
        ),
    ]
