# Generated by Django 4.2.6 on 2023-11-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_user_send_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='send_notifications',
        ),
        migrations.AddField(
            model_name='topic',
            name='notify_me',
            field=models.BooleanField(default=False),
        ),
    ]
